CustomWaterfall: add min functionality
catchpoint/WebPageTest pull request #3057
Opened 2024-04-11 16:54 UTC by jspurlin

Prior to this PR users could only set a max time to filter on when creating custom waterfalls. This meant that custom waterfalls always started at t=0 even if what you cared about didn't start until the t=5s mark

This PR adds the ability to optionally specify a min time to filter on in addition to setting a max and requests to filter on.

I verified that the custom filter scales correctly in app parts (Requests, CUP Utilization, Bandwidth, Browser Main Thread, and Long Tasks)

For example, if I care about the 5-10s range of the waterfall this is what it looks like

# Before
![image](https://github.com/jspurlin/WebPageTest.agent/assets/7033561/732438f3-68cc-4366-95d1-20b9495f6431)

# After
![image](https://github.com/jspurlin/WebPageTest.agent/assets/7033561/3e6b816f-ff4b-4747-aa09-3d1203eddb63)

This is a fix for [Add ability to specify min/start time for custom waterfalls #3042](https://github.com/catchpoint/WebPageTest/issues/3042)

2024-04-11 16:56 UTC, jspurlin commented
@pmeenan / @vibaldem  FYI, this PR is for #3042

2024-04-19 18:53 UTC, arthesh commented
Tagging @mjkozicki , @claud-io , would appreciate if you could review this PR and provide feedback.

2024-04-19 21:23 UTC, pmeenan approved these changes
LGTM.

`Minimum` time feels a bit off and `Start` seems more appropriate but given that the end is called `Maximum` it is appropriate to keep it aligned.

Thanks for doing this, it's been a long-standing request and I've been dreading going through the scaling code. The change looks nice and clean.

2024-04-22 15:45 UTC, jspurlin commented
@mjkozicki ...PING... Can you review (and merge if things look good)?

2024-05-22 16:46 UTC, jspurlin commented
@mjkozicki @claud-io  ...PING, PING... Can you review (and merge if things look good)?

2024-05-22 16:58 UTC, claud-io commented
Hello @jspurlin we are testing it, will let you know once is done. Thanks

2024-05-23 16:14 UTC, claud-io requested changes
@jspurlin seems page sometimes break when min >= max or with neg numbers, can you please add check for those cases? thanks

2024-06-05 13:49 UTC, claud-io commented
@jspurlin thanks, going to start testing it

2024-06-06 09:12 UTC, lbartoli79 commented on www/waterfall.inc
> +    if (@$_REQUEST['min'] > 0 && @$_REQUEST['min'] < @$_REQUEST['max']) {
Can you address `$max_ms` effective value? As is `min` it only works if a `max` value is provided

2024-06-06 09:14 UTC, lbartoli79 requested changes
We should not draw vertical lines on first column

![image](https://github.com/catchpoint/WebPageTest/assets/142893024/fc4c3300-9898-4fc1-96c8-1cbc4c608f8a)

2024-06-10 16:26 UTC, jspurlin commented
> We should not draw vertical lines on first column
> 
> ![image](https://private-user-images.githubusercontent.com/142893024/337201750-fc4c3300-9898-4fc1-96c8-1cbc4c608f8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzY5NzYsIm5iZiI6MTcxODAzNjY3NiwicGF0aCI6Ii8xNDI4OTMwMjQvMzM3MjAxNzUwLWZjNGMzMzAwLTk4OTgtNGZjMS05NmM4LTFjYmM0YzYwOGY4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxNjI0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjZhODEyNmVkOTViNmNiYmQ5ZjkyMDJmYTNiODU0ZjY4MDFlNzJjYTdmMjNkYTUwYmZhODU2MzQzNjIwMjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o-EejQoC7u_lMQHlxZrvE6fmWExFEwp3EzyWa3j-e7I)

@lbartoli79 Done. I've made sure to account for the case where min is provided but max is not and not to draw lines < min_ms

2024-07-09 15:21 UTC, jspurlin commented
...PING...

@claud-io and @lbartoli79

2024-07-15 09:55 UTC, lbartoli79 approved these changes

2024-07-15 10:01 UTC, merged